INSERT INTO TB_AUTHORITY (NAME, CREATED_BY, LAST_MODIFIED_BY) VALUES ('ROLE_ADMIN', 'SYSTEM', 'SYSTEM');
INSERT INTO TB_AUTHORITY (NAME, CREATED_BY, LAST_MODIFIED_BY) VALUES ('ROLE_USER', 'SYSTEM', 'SYSTEM');

INSERT INTO TB_USER (ID, USERNAME, PASSWORD, CREATED_BY, LAST_MODIFIED_BY) VALUES ('1', 'admin', '123456', 'SYSTEM', 'SYSTEM');

INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES ('1', 'ROLE_ADMIN');
INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES ('1', 'ROLE_USER');
